In [1]:
import numpy as np

In [3]:
X= np.array([[0,0],[0,1],[1,0],[1,1]])
Y= np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [25]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [15]:
#no hidden layer weights
weights = 2*np.random.random((2,1))-1
bias = 2* np.random.random(1)-1
weights, bias

(array([[-0.41853201],
        [-0.08642583]]), array([-0.68469098]))

In [17]:
# forward propagation without any hidden layer
output0= X
output = sig(np.dot(output0, weights)+bias)
output

array([[ 0.33521513],
       [ 0.31623757],
       [ 0.24913649],
       [ 0.23332175]])

In [23]:
wh = 2*np.random.random((2,2))-1
bh = 2*np.random.random((1,2))-1
wo = 2*np.random.random((2,1))-1
bo = 2*np.random.random((1,1))-1

In [24]:
output0 = X
outputHidden = sig(np.dot(output0, wh)+ bh)
output = sig(np.dot(outputHidden, wo) +bo)
output

array([[ 0.69001163],
       [ 0.66978961],
       [ 0.71215479],
       [ 0.69175764]])